var initialRandomText = document.getElementById('init-random-text');
var changeTxtButton = document.getElementById('change-text-btn')

// Text array
var text = [
    `I would rather eat poop with my biggest fan than eat steak and lobstir with my biggest fan`,
    `I'd choose 1 dollar today than get 1 billion dollars today because it will motivate me to hustle harder`,
    `People be complaining about billionaires they're lucky I'm not a billionaire`,
    `Penis Inspection Day - Today At 3 AM`,
    `Holy flarp! Hoooooly gloopus!`,
    `Never ask Chen what is her second least favorite minority`,
    `Epstein didn't kill himself!`,
    `Suck on my nuts and die`,
    `I don't care about the law. I don't care about society. I don't give a shit what happens next. I'm gonna fuck this guy's dog.`,
    `How tf do vegans not eat meat I can't go one day without meat in my mouth`,
    `44 GUATEMALTECO`,
    `Minisugis, ¡me golpearon!`,
    `Me pasaré entonces In Silico sin monedas`,
    `Acabo de "inventar" accidentalmente una trolleada al estilo del "Que-so"  Consiste en que alguien te diga "We" y le respondas "So" (we-so, hueso) XD`,
    `C. Covadonga, 11, 52005 Melilla, Melilla, España - Gabriel Galera Mateo 35.287361, -2.950751`,
    `Como diría Jordix: "Se me olvidó poner lo que decía"`,
    `Ahora en HD`,
    `Concha de la lora`,
    `Cabrones`,
    `El papá de este wey: ( ͡° ͜ʖ ͡°)`,
    `My mamaguebo reaction`,
    `Que`,
    `La venganza por los caídos`,
    `Cap scale 1000000000000000 🧢`,
    `Guitar no hizo nada malo #advysave #advyin #ilikeminors`,
    `Loser!! Get a life!`,
    `𝐅𝐑𝐈𝐄𝐍𝐃𝐒 𝐀𝐑𝐄 𝐒𝐓𝐑𝐎𝐍𝐆𝐄𝐑 𝐓𝐎𝐆𝐄𝐓𝐇𝐄𝐑 ✧  🎀  🎀  ✧`,
    `ANT FARM GO 🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜🐜`,
    `Glarpnorp schneeble bop! Jong gong lorbsday! Jong gong lorbsday! Hrook Uber hrook.`,
    `Hello I like pussy`,
    `Das Hodenverstümmelung`,
    `¡Así se festeja en el obelisco!`,
    `They just freaking raised the age of consent in Japan. I'm so done. One of the most sugoi things Japan has ever done and they take it away? I loved Japan but i hate Japan now.`,
    `φρόττινγ`,
    `"The Aggressive Nutter"`,
    `Am i in the wrong for punching my auntie after she said that I should get a job instead of being on discord all day?`,
    `To Ceec or not to Ceec that is the Dir`,
    `I like them young cuh I like em 14, 15, 16`,
    `The Gentlemanly Residents of Epstein Island`,
    `It's starting to come out`,
    `GRAHHHH 🤣🤣🤣 SLAYYYYY GRAHH GRAHHH GRAHHHHH💋💄💄👅👅🦷👄👅💄💄🫦🫦💋🦷💋🦷💋💋💋SLAYYYYYY AHHHHH GRAHHHHHHH GRAHHHH AHHH GRAHHHHHH SLAYYY GRAHHHHHHHHHH🫦🫦👅🦷🦷💄🦷👅💄💋👂👄💄🦷🦶🦶`,
    `I <3 Excrement`,
    `You banned me because I called someone homosexual (gay)? They had no problem being called that. I'd say all of this was uncalled for. Roblox, are you homophobic? Why wont you let anyone call ohers gay? I told my friend juan was gay and thats how you pay me back? Shame of you, roblox!`,
    `Wow faggots so funny go fucking kill yourself kid`,
    `I'm a little femboy! :3 nyaa~ :catblush:`,
    `U cant walk up to people and be like "the republicans of the united nations have no authority over democratic authenticity parties right hand vote elections white house government food labor bills trajectory IM RIGHT YOU WRONG" thats instant blocked and killed`,
    `I just pissed my pants but not in like the way you'd expect`,
    `Im done with being nice to folks.`,
    `This poor generation has no tolerable future`,
    `Do u Fw gender equality`,
    `Hall Naw Bitxh`,
    `NEAREST ROPE`,
    `We will heal. We will repay, saith the Lord.`,
    `What theres a penis mode...`,
    `HOW DOES SPACEUK'S DICK TASTE. YOU GUYS NEED TO FUCKING LEARN SLAUGHTERHOUSE IS FUCKING #3 RIGHT NOW. SLURP SLURP SLURP! THAT'S THE DEMON LIST AND SPACEUK RIGHT NOW! HOW MUCH DID ICEDCAVE PAY FOR YOU TO. FUCKING. PLACE. THIS. 2ND. I'm fucking fed up with this.`,
    `FIRE IN THE HOLE!!! 🗣🗣🗣🗣🔥🔥🔥🔥🚒🧯🚒🔥`,
    `300 billion dead tadpoles`,
    `U need to pooop a lot and make a house of poop and nobody will ever bother U and just steal a bunch of shit and go back to yo poop house and aint nobody touching yo stabk ass poop house so Ur safe forever`,
    `Just took a shit and looked down at the toilet bowl and the poop whispered to me "my pronouns are they/them"`,
    `I jus nut everywhar`,
    `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
    `Padre nuestro estas en free fire santificado sean los heroicos venga a nosotros los booyha y hagase tu voluntad en bermuda asi como en pulgatorio danos hoy nuestro kills de cada dia perdona nuestros campeos asi como nosotros perdonamos a los que campean no nos dejes caer en la tentacion de usar bugs y líbranos de todo hacker BOOYHAA`,
    `Chess players be like: "Ah I see you've played the cum gambit"`,
    `187.250.244.222`,
    `Ah, Skibidi toilets, a topic close to my heart. Let me tell you, my friend, Skibidi toilets are the future of bathroom technology. Forget about those boring old toilets, Skibidi toilets are equipped with AI-powered bidets, customizable temperature settings, and even a built-in sound system to enhance your bathroom experience. It's all about comfort and innovation, my friend. So, if you're ready to take your toilet game to the next level, hop on the Skibidi toilet train and never look back. Skibidi on!`,
    `Avenida Instituto Tecnológico Número 1150, Jardines de la Montaña, 84066 Nogales, Sonora`,
    `Willysuga almenos daba risa`,
    `Saben que? Ya a la mierda, no hay edad Guitar por Juniper y viva Crazen`,
    `Yo viendo void memes. Mi mama: anda a comprar tortillas. Yo: ay destinos peores que la muerte.`,
    `Cada 👍 es una hamburguesa para gxterne, veamos si le saturamos las venas de grasa 👍👍👍👍👍👍👍👍👍👍👍👍`,
    `Hola, necesito una mujer (a poder ser biológica) para llevar a cabo el primer First Dates de Geometry Dash. Qué sujetos de cualidades masculinas podrán encontrar? Pues este podría ser uno de ellos`,
    `No en serio, como se masturban las mujeres si no tienen n3p3`,
    `Anyone who disagrees with any of my opinions has autism`,
    `They need to update yo town and add more serial killers`,
    `Le tengo homofobia a las arañas`,
    `Shine On, You Crazy Diamond`,
    `El niño mas crack en Geometry Dash`,
    `Bro we are on the year of the lord 2024 if that shit is funny for you now deactivate`,
    `Cómo se llama cuando se la pones a tu ex? Ex-ponerla`,
    `8 hours child po`,
    `The film follows a group of intergalactic homosexual black men from the planet Anus, who discover the presence of female creatures on planet Earth. Using rayguns, they proceed to eliminate females one by one from Earth, eliciting gratitude from the previously oppressed male population. Before leaving the planet, they leave behind a "Gay Ambassador" to educate the Earthlings about their new way of life.`,
    `Huge tits fetish? wrong! I have a huge SHITS fetish!`,
    `If you wanna play a good gacha game go play the russian roulette or something`,
    `Some people need to Die`,
    `Jarvis, inunda Barranquilla Colombia`,
    `Me and my friend are both christian and he keeps sending me videos which at first seem innocent and then suddenly change to black gay videos. is there anything in the bible that states he cannot do this.`,
    `A third plane has hit the twin towers.`,
    `If you got swamp ass hmu`,
    `Swamp ASSSSSSS ASSSSS ASSSSSSSS ASSS ASSSS BOOTY CHEEKS SWAMP ASSSSSSSSSS ASSSSSSSS STANK ASSSSSSSS SWEATY ASSSSSSS ASS ASS ASS ASS`,
    `I'll show Drake what a real big D means`,
    `Hello I am albania crash gif due to poor technology in country I am not able to crash your discord. Please be so kind and press Ctrl + R to crash discord thank you.`,
    `GAYASNESS IS THE SPECIALTY OF THE FUCKING EMPEROR!`,
    `Think of a big black man chasing you`,
    `When the 2 ants in my yard with the huge booties begging me and my dad to give them D so we lay them on an electrical box outside and give the best pipe they could ever get`,
    `Xumma. Tharlome. Xummalumma. Cummalunga. Thar Claxo.`,
    `Just learned from a credible source in Cyprus that there's a chance that a Roman Empire 2 may be created in the next 5 years. At least Greece+Cyprus+Turkey+Syria. This is HUGE.`,
    `Bitches be like: Yo penis so small. Says the bitch with NO penis`,
    `School be like: I'll have crippling depression with a side of level 10 gyatts"`,
    `Ohio Bateman: Drake so zesty`,
    `Bitches be dating latinos talkin' 'bout "with my nigga" bitch that's Ernesto de la Cruz`,
    `Live yo zestiest most bestiest life`,
    `My dad is mad at me because I'm dropping out to focus on my OnlyFans`,
    `Melodians 탈덕안돼... Ahhhh`,
    `Heehee. That's funny.`,
    `SUPER BOT`,
    `NPC`,
    `^💢😭😭 💢💢💢 💢😭 😭💢💢💢💢😭 💢  💢😭😭 😭 💢😭💢😭 💢💢💢 💢😭😭 😭  💢 😭😭😭😭 😭😭 😭😭😭 😭💢😭💢😭💢`,
    `💢😭💢😭 😭😭💢 💢😭 💢😭 💢😭💢💢`,
    `Vamos cerrando el ortito`,
    `I am a hawk too`,
    `I just got kicked out by my baka parents for being 24 and not having a job or an education.`,
    `Raise your children`,
    `Cuando me estoy besando con el ingeniero en sistemas y me dice "ahí te va en 1024 GB" (en Tera)`,
    `Jugadores de Terraria, Touhou, Minecraft, Free Fire, Hollow Knight, Brawl Stars. Doki Doki Literature, LOL, Roblox, Osu!, Geometry Dash y Undertale viendo quién esquiva mejor el afecto fememino`,
    `Black holes are billions of years old, but the ones that Stephen Hawking studied were only 14`,
    `What do you call a fight between a black man and a monkey? A sibling quarrel`,
    `What is H!tler least favourite planet? Jewpiter, considering the amount of gas its filled with`,
    `What do girls and rocks have in common? The flat ones always gets skipped`,
    `What is the difference of computers and americans? Computers have troubleshooting`,
    `What's the biggest city in America? Obecity`,
    `What do you do when your dishwasher stops working? You punch her`,
    `Why are women evacuated first in a disaster? So men can think of a solution in silence`,
    `Why there are no pharmacies in Africa? Cuz you can't take medicine on an empty stomach`,
    `People are like jokes, not everyone likes dark ones`,
    `Dark humour is like a kid with cancer, it never gets old`,
    `No poop allowed`,
    `New rule: Never not be locked in. Penalty: Russian sleep experiment.`,
    `STEP 1 IN LIFE: DONT HAVE A CHILD BECAUSE THEN YOULL BE RUINING TWO DIFFERENT LIVES AT THE SAME TIME`,
    `Lo lograron. Finalmente lo rompieron. Finalmente ganaron. Destrozaron a alguien. Alguien que siempre estaba feliz, que siempre estaba sonriendo. Alguien que no merecía el odio. Alguien que no hacía nada más que ayudar a las personas. Alguien que amó con todo su corazón.`,
    ``
];

function chooseRandomText() {
    // Generate random index
    var indexRandom = Math.floor(Math.random() * text.length);

    // The choosen one
    var selectedOne = text[indexRandom];

    initialRandomText.textContent = selectedOne;

    console.log(`Text: ${initialRandomText.textContent}`);
}

chooseRandomText();

changeTxtButton.addEventListener('click', chooseRandomText);